### ISSUE TITLE
Capstone review screenshots

### ISSUE THREAD

**Issue by bini-i** [Shaher-11/Academy#2]
![image](https://user-images.githubusercontent.com/61377322/110575381-d03ddc00-816f-11eb-9788-4b9c32c52d04.png)
![image](https://user-images.githubusercontent.com/61377322/110575423-e64b9c80-816f-11eb-8477-69b9a90188f7.png)

![image](https://user-images.githubusercontent.com/61377322/110576982-c5d11180-8172-11eb-9274-8e559a5ec21d.png)
![image](https://user-images.githubusercontent.com/61377322/110576268-89e97c80-8171-11eb-930d-22591dc25fa9.png)

![image](https://user-images.githubusercontent.com/61377322/110576599-172cd100-8172-11eb-8d52-4989e5d13f7f.png)
![image](https://user-images.githubusercontent.com/61377322/110576618-201da280-8172-11eb-9cdc-aa9c40603d61.png)

![image](https://user-images.githubusercontent.com/61377322/110577380-940c7a80-8173-11eb-8862-373b9ba8344b.png)
![image](https://user-images.githubusercontent.com/61377322/110577352-8820b880-8173-11eb-9fd4-74958baccc52.png)

![image](https://user-images.githubusercontent.com/61377322/110577860-96230900-8174-11eb-812e-725343e419a3.png)

**Comment by Shaher-11** [comment]
Add the required sections and modified the existing ones
